global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 3s
  scrape_timeout: 3s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    - pushgateway:9091
    - exporter:9187

- job_name: controller
  honor_timestamps: true
  scrape_interval: 3s
  scrape_timeout: 3s
  metrics_path: /api/v2/metrics
  scheme: http
  static_configs:
  - targets:
    - controller:11000
